// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_8ZQ84i-VMFMVDMoexYcgFjxMF1rnbWc',
    appId: '1:881348166521:android:3a2cf658e71fb5d3a2e5a8',
    messagingSenderId: '881348166521',
    projectId: 'smart-study-planner-23497',
    storageBucket: 'smart-study-planner-23497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjKvJzbYNLbRmgcVhNADvfFduD8fmeK04',
    appId: '1:881348166521:ios:23dc12143cee8afda2e5a8',
    messagingSenderId: '881348166521',
    projectId: 'smart-study-planner-23497',
    storageBucket: 'smart-study-planner-23497.firebasestorage.app',
    iosBundleId: 'com.example.smartStudyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOFLiwnv7wTUreiGlM4JVB3eqWy6-2zEY',
    appId: '1:881348166521:web:73249b1cb4e827a2a2e5a8',
    messagingSenderId: '881348166521',
    projectId: 'smart-study-planner-23497',
    authDomain: 'smart-study-planner-23497.firebaseapp.com',
    storageBucket: 'smart-study-planner-23497.firebasestorage.app',
    measurementId: 'G-GZ0GW9PMP7',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOFLiwnv7wTUreiGlM4JVB3eqWy6-2zEY',
    appId: '1:881348166521:web:73249b1cb4e827a2a2e5a8',
    messagingSenderId: '881348166521',
    projectId: 'smart-study-planner-23497',
    authDomain: 'smart-study-planner-23497.firebaseapp.com',
    storageBucket: 'smart-study-planner-23497.firebasestorage.app',
    measurementId: 'G-GZ0GW9PMP7',
  );

}